[package]
name = "hiperia_program"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
name = "hiperia_lottery"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
sha2 = "0.10.8"
