[package]
name = "donation_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "donation_program"

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
sha2 = "0.10"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []

idl-build = ["anchor-lang/idl-build"]